hmscrm/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView, PasswordResetDoneView, \
    PasswordResetCompleteView, PasswordChangeView, PasswordChangeDoneView, PasswordResetConfirmView
from django.urls import path, re_path
from django.urls import include
from django.conf import settings
from django.views.static import serve
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('hotel.urls')),
    re_path(r'^accounts/login/$', LoginView.as_view(template_name='registration/login.html'), name="login"),
    re_path(r'^accounts/logout/$', LogoutView.as_view(template_name='registration/logout.html'), LogoutView.next_page, name="logout"),
    re_path(r'^accounts/password/reset/$', PasswordResetView.as_view(template_name='registration/password_reset_page.html'), name='password_reset'),
    re_path(r'^accounts/password/reset/done/$', PasswordResetDoneView.as_view(template_name='registration/passwordreset_pagedone.html'), name='password_reset_done'),
    re_path(r'^accounts/password/reset/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/',PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirmpage.html'), name='password_reset_confirm'),
    re_path(r'^accounts/password/reset/complete/$', PasswordResetCompleteView.as_view(template_name='registration/password_reset_completepage.html'), name='password_reset_complete'),
    re_path(r'^accounts/password/change/$',PasswordChangeView.as_view(template_name = 'registration/change-password.html'), name='password_change'),
    re_path(r'^accounts/password/change/done/$',PasswordChangeDoneView.as_view(template_name='registration/change-password-done.html'),
            name='password_change_done'),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

hotel/urls.py
from django.conf.urls import url
from django.contrib.auth.views import LogoutView, LoginView


from . import views
from django.urls import path, re_path

from .views import hotelSearch,GeneratePDF

app_name = 'hotel'
urlpatterns = [
    path('', views.home, name='home'),
    re_path(r'^home/$', views.home, name='home'),
    # ex: /customer_list/
    path('about/', views.about, name='about'),
    path('hotels_list/', views.hotels_list, name='hotels_list'),
    path('<int:id>/<slug:slug>/', views.hotel_details, name='hotel_details'),
    path('<int:hotel_id>/<slug:hotel_slug>/<int:RoomNumber>/', views.room_details, name='room_details'),
    path('register/', views.register, name='register'),
    url(r'(?P<hotel_id>[0-9]+)/(?P<RoomNumber>[0-9]+)$/', views.bookroom, name='bookroom'),
    path('book/<int:hotel_id>/<int:RoomNumber>/', views.bookroom, name='bookroom'),
    url(r'^mybookings/$', views.mybookings, name='viewbookings'),
    url(r'^mybookings/cancel/(?P<id>[0-9]+)$', views.cancelbooking, name='cancelbooking'),
    url(r'^search$', hotelSearch.as_view(), name='hotelsearch'),
    url(r'^mybookings/(?P<id>[0-9]+)/pdf$', GeneratePDF.as_view(), name='gpdf'),
    

]

hotel/models.py
from django.utils import timezone
from django.urls import reverse
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


# Stores all the hotel details and is used to query hotels.
class Hotels(models.Model):
    Name = models.CharField(max_length  = 255)
    Description = models.TextField(max_length=700)
    Amenities = models.TextField(max_length=150)
    Address = models.CharField(max_length  = 255)
    City = models.CharField(max_length  = 255)
    Country = models.CharField(max_length  = 255)
    state = models.CharField(max_length=50)
    zipcode = models.CharField(max_length=10)
    TelephoneNumber = models.CharField(max_length=12)
    slug = models.SlugField(max_length=100, unique=True)
    created_date = models.DateTimeField(default=timezone.now)
    updated_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'Hotel'
        verbose_name_plural = 'Hotels'

    def __str__(self):
         return self.Name

    def created(self):
        self.created_date = timezone.now()
        self.save()

    def updated(self):
        self.updated_date = timezone.now()
        self.save()

    def get_absolute_url(self):
        return reverse('hotel:hotel_details', args=[self.id, self.slug])


class Images(models.Model):
    hotel = models.ForeignKey(Hotels,on_delete=models.CASCADE,related_name='imagesofhotel')
    image = models.ImageField(upload_to='hotelimages/%Y/%m/%d', blank=True)
    updated_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'Images'
        verbose_name_plural = 'Images'

    def updated(self):
        self.updated_date = timezone.now()
        self.save()


# Stores the Hotels rooms
class Rooms(models.Model):
    hotel = models.ForeignKey(Hotels,on_delete=models.CASCADE)
    RoomNumber=models.IntegerField(max_length=10,primary_key=True)
    RoomType = models.CharField(max_length = 255)
    Capacity = models.IntegerField(default = 0)
    BedOption = models.CharField(max_length = 255)
    RoomSize=models.CharField(max_length=10)
    Amenities = models.TextField(max_length=150)
    Price= models.IntegerField(default = 0)
    slug = models.SlugField(max_length=100, unique=True)
    image = models.ImageField(upload_to='hotelroomimages/%Y/%m/%d', blank=True)
    created_date = models.DateTimeField(default=timezone.now)
    updated_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'Room'
        verbose_name_plural = 'Rooms'

    def __str__(self):
        return self.RoomType

    def get_absolute_url(self):
        return reverse('hotel:room_details', args=[self.hotel.id,self.hotel.slug,self.RoomNumber])



#Create a Reservation Model which stores booking details


class Reservation(models.Model):
    hotel = models.ForeignKey(Hotels,on_delete=models.CASCADE)
    room = models.ForeignKey(Rooms,on_delete=models.CASCADE)
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    guestFirstName = models.CharField(max_length  = 255)
    guestLastName = models.CharField(max_length  = 255)
    email = models.EmailField(max_length=70)
    phonenumber=models.IntegerField(max_length=10)
    CheckIn = models.DateField()
    CheckOut = models.DateField()
    totalPrice = models.IntegerField(default = 0)

    class Meta:
        verbose_name_plural = 'Reservation'

    def __str__(self):
         return self.user.username

hotel/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
import datetime
from .models import Reservation

class RegisterForm(UserCreationForm):
    password1 = forms.CharField(label='Password',
                               widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repeat password',
                                widget=forms.PasswordInput)
    email = forms.EmailField(label='Email', max_length=254, help_text='Required. Enter a valid email address.')
    first_name = forms.CharField(max_length=50)
    last_name = forms.CharField(max_length=50)

    class Meta:
        model = User
        fields = ('username', 'email', 'first_name','last_name','password1', 'password2')


class Booking(forms.ModelForm):
    class Meta:
        model = Reservation
        fields = ('guestFirstName', 'guestLastName', 'email', 'phonenumber', 'CheckIn', 'CheckOut',)
        widgets = {
        'CheckIn': forms.DateInput(attrs={'class': 'datepicker' }),
        'CheckOut': forms.DateInput(attrs={'class': 'datepicker'})
        }

    def clean(self):
        cleaned_data = super(Booking, self).clean()
        checkindate = cleaned_data.get("CheckIn")
        checkoutdate = cleaned_data.get("CheckOut")

        if checkindate and checkoutdate:
            if checkoutdate < checkindate:
                raise forms.ValidationError("Checkout date cannot be earlier than Checkin Date!")
        return cleaned_data

hotel/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404,redirect
from .forms import *
from .models import Hotels,Rooms,Images,Reservation
from django.utils import timezone
from django.views import View
from django.http import HttpResponse
from django.core.exceptions import ValidationError
import datetime
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.template.loader import get_template
from .utils import render_to_pdf

# Create your views here.
now = timezone.now()


def home(request):
    return render(request, 'hotel/home.html', {'hotel': home})


def about(request):
    return render(request, 'hotel/about.html', {'hotel': home})


def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return render(request,
                          'registration/registerdone.html',
                          {'form': form})
    else:
        form = RegisterForm()
    return render(request, "registration/register.html", {"form": form})

@login_required()
def hotels_list(request):
    hotels = Hotels.objects.all()
    images = Images.objects.all()
    return render(request,'hotel/hotels_list.html',{'hotels':hotels,'images': images})

@login_required()
def hotel_details(request, id, slug):
    hotel = get_object_or_404(Hotels,id=id, slug=slug,)
    images = Images.objects.filter(hotel=hotel)
    rooms = Rooms.objects.filter(hotel=hotel)
    return render(request, 'hotel/hotel_details.html',
                  {'hotel': hotel,'images':images,'rooms':rooms})

@login_required()
def room_details(request, hotel_id, hotel_slug,RoomNumber,):
    hotel = get_object_or_404(Hotels,id=hotel_id, slug=hotel_slug)
    room = Rooms.objects.get(hotel=hotel,RoomNumber=RoomNumber)
    return render(request, 'hotel/room_details.html',
                  {'hotel': hotel,'room':room })

@login_required()
#Shows the user thier previous bookings.
def mybookings(request):
    bookings = Reservation.objects.filter(user = request.user)
    return render(request, 'hotel/mybookings.html', {'bookings':bookings,'now': datetime.datetime.now()})


# Allows a user to cancel their previous bookings , deleting a booking onclick.
@login_required()
def cancelbooking(request,id):
    booking = get_object_or_404(Reservation,id = id)
    booking.delete()
    return redirect('hotel:viewbookings')

@login_required()
def bookroom(request,hotel_id,RoomNumber):
    if request.method == 'POST':
        form = Booking(request.POST)
        CheckinDate = request.POST['CheckIn']
        print("check in", CheckinDate)
        CheckoutDate = request.POST['CheckOut']
        print("check out", CheckoutDate)
        Checkin = datetime.datetime.strptime(CheckinDate, "%m/%d/%Y").date()
        Checkout = datetime.datetime.strptime(CheckoutDate, "%m/%d/%Y").date()
        if form.is_valid():
            currentuser = request.user
            hotel = Hotels.objects.get(id=hotel_id)
            room = Rooms.objects.get(RoomNumber=RoomNumber)
            # check wether the dates are valid
            # case 1: a room is booked before the check_in date, and checks out after the requested check_in date
            case_1 = Reservation.objects.filter(room=room, CheckIn__lte=Checkin, CheckOut__gte=Checkin).exists()

            # case 2: a room is booked before the requested check_out date and check_out date is after requested check_out date
            case_2 = Reservation.objects.filter(room=room, CheckIn__lte=Checkout, CheckOut__gte=Checkout).exists()

            case_3 = Reservation.objects.filter(room=room, CheckIn__gte=Checkin, CheckOut__lte=Checkout).exists()

            # if either of these is true, abort and render the error
            if case_1 or case_2 or case_3:
                messages.error(request, 'Room is not available on that dates')
                return render(request, "hotel/booking.html",
                              {'form': form})

            reservation = form.save(commit=False)
            reservation.user=currentuser
            reservation.hotel=hotel
            reserved = False
            timedeltaSum = Checkout - Checkin
            print("timedeltaSum", timedeltaSum)
            StayDuration = timedeltaSum.days
            print("StayDuration", StayDuration)
            price = room.Price
            TotalCost = StayDuration * price
            print("TotalCost", TotalCost)
            reservation.totalPrice=TotalCost
            reservation.created_date = timezone.now()
            reservation.room = room
            reservation.save()
            return render(request, 'hotel/bookingsuccess.html',
                              {'reservation': reservation})
    else:
        form = Booking()
    return render(request, 'hotel/booking.html', {'form': form})




## Generates a PDF using the render help function and outputs it as invoice.html
class GeneratePDF(View):
    def get(self,request, *args, **kwargs):
        reservation = Reservation.objects.get(id= self.kwargs['id'])
        template = get_template('hotel/invoice.html')
        context = {"reservation":reservation}
        html = template.render(context)
        pdf = render_to_pdf('hotel/invoice.html', context)
        return HttpResponse(pdf,content_type='application/pdf')

class hotelSearch(View):
    def get(self,request):
        return render(request, 'hotel/search.html')
    def post(self,request):
        print("Searchterm entered post ")
        #Searchterm = request.POST.get("searchitem")
        Searchterm=request.POST['searchitem']
        print("Searchterm",Searchterm)
        if Searchterm:
            hotels_list = Hotels.objects.filter(Q(City__icontains=Searchterm) | Q(Country__icontains=Searchterm)
            | Q(state__contains=Searchterm)| Q(Name__icontains=Searchterm))
            print("hotels_list",hotels_list)
            if hotels_list:
                context = {'hotels': hotels_list}
                return render(request, 'hotel/hotels_list.html', context)
            else:
                messages.error(request,'No results found')
        return render(request, 'hotel/search.html')

hotel/templates/hotel/about.html
{% extends "hotel/base.html" %}
{% load static %}
{% block content %}
 <div class="ui main container">
 <head>
     <style>
        body {
            background-color: white;
            height: auto;
        }
        h2 {
            color:#d5242f ;
        }
     </style>
 </head>
<h2 >What We Do</h2>

<p> Hotel Management site  provides expert facilities and compassionate care to all who need it – regardless of their age, station in life or available resources. our mission is to provide extensive facilities,care  that provides peace of mind, quality of life and independence.

For more than 10 years, we have helped people to  build a stronger, healthy environment through innovative programs delivered across the lifespan. Each year, our system helps nearly 50,000 people to live higher quality and more independent lives by providing innovative services that meet the unique services to the members.
</p>
<h2>Our  service areas include:</h2>

<p>
 It provides healthy environment and quality of life for all individuals to achivve  the highest quality of life.</p>
 </div>
{% endblock %}

hotel/templates/hotel/base.html
{% load static %}

<html lang="en">
<head>
    <title>Hotel  Services</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/portfolio.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>



   <link rel="stylesheet" href="http://code.jquery.com/ui/1.11.0/themes/smoothness/jquery-ui.css">
        <script src="http://code.jquery.com/jquery-1.9.1.js"></script>
        <script src="http://code.jquery.com/ui/1.11.0/jquery-ui.js"></script>





<script>
$(document).ready(function() {
    $('.datepicker').datepicker({
    minDate : 0
});
});
</script>

    <style>
        /* Remove the navbar's default margin-bottom and rounded borders */
        .navbar {
            margin-bottom: 0;
            border-radius: 0;
        }

        /* Set height of the grid so .sidenav can be 100% (adjust as needed) */
        .row.content {
            height: 450px
        }

        /* Set gray background color and 100% height */
        .sidenav {
            padding-top: 20px;
            background-color: #f1f1f1;
            height: 100%;
        }

        /* Set black background color, white text and some padding */
        footer {
            background-color: #555;
            color: white;
            padding: 15px;
        }

        /* On small screens, set height to 'auto' for sidenav and grid */
        @media screen and (max-width: 767px) {
            .sidenav {
                height: auto;
                padding: 15px;
            }

            .row.content {
                height: auto;
            }
        }
    </style>
</head>
<body id="app-layout">
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header">

            <!-- Collapsed Hamburger -->
            <button type="button" class="navbar-toggle" data-toggle="collapse"
                    data-target="#myNavbar">
                <span class="sr-only">Toggle Navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

            <!-- Branding Image -->
            <a class="navbar-brand" href="/">
                Hotel Management Service
            </a>
        </div>
        <div class="collapse navbar-collapse" id="myNavbar">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'hotel:home' %}">Home</a></li>

            </ul>
             <ul class="nav navbar-nav">
                 <li><a class="nav-item nav-link" href={% url 'hotel:about' %}>About</a></li>
               <li><a href="{% url 'hotel:hotelsearch'%}">Search Hotels</a></li>

            </ul>
             {% if user.is_authenticated %}
             <ul class="nav navbar-nav">

                    <li><a href="{% url 'hotel:viewbookings'%}">View Your Bookings</a></li>

            </ul>
            {% endif %}
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu" role="menu">
                            <li><a href="{% url 'logout' %}"><i class="fa fa-btn fa-sign-out"></i>Logout</a></li>
                            <li><a href="{% url 'password_change' %}"></i>Password Change</a></li>
                        </ul>
                    </li>
                {% else %}
                    <li><a href="{% url 'login' %}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
                    <li><a href="{% url 'hotel:register' %}"><span class="glyphicon glyphicon-log-in"></span> Sign Up</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>
 {% block content %}
{% endblock %}

</body>
</html>

hotel/templates/hotel/booking.html
{% extends 'hotel/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <h1>Booking A Reservation</h1>

    {% if messages %}
<ul style="color:red;font-size: 50px;">
   {% for message in messages %}
	   <li>{{ message }}</li>
   {% endfor %}
</ul>
{% endif %}


    <div class="container">
    <form method="POST" class="form-group">{% csrf_token %}
        {% csrf_token %}
          {{ form|crispy }}
        <button type="submit"  class="btn btn-success">Book Now</button>
    </form>
     <p><a href="{% url 'hotel:hotels_list' %}">View the hotels list</a></p>
    </div>
{% endblock %}

hotel/templates/hotel/bookingsuccess.html
{% extends 'hotel/base.html' %}
{% block content %}
    <div class="container">
    <h1>Booking sucessfully done.Find your Booking Details </a> here. </h1>

    <div class="row">
    <div class="col-md-6 col-md-offset-3 ">


      <a class="btn btn-sm btn-danger pull-right" href="{% url 'hotel:cancelbooking' reservation.id %}">Cancel</a>
        <a  class="btn btn-sm btn-default pull-right" href="{% url 'hotel:gpdf' reservation.id %}">Download PDF</a>
        <p>Hotel Name: {{reservation.hotel.Name}}</p>
        <p>Room Type :{{reservation.room.RoomType}}.  </p>
      <p>Room Number: {{reservation.room.RoomNumber}}.  </p></p>
        <p>Guest Name : {{reservation.guestFirstName}} {{booking.guestLastName}}.  </p>
        <p>Check-in Date :{{reservation.CheckIn}}.  </p>
        <p>Check-out Date: {{reservation.CheckOut}}.  </p>
        <p>Total Price : ${{reservation.totalPrice}}.  </p>

    </div>
    </div>
    </div>
{% endblock %}

hotel/templates/hotel/home.html
{% extends "hotel/base.html" %}
{% load static %}
{% block content %}
 <html>
   <body>


      {% if user.is_authenticated %}
                <div class="page-container">

                    <h2 class="top-menu">Hello {{ user.username }},</h2>
                    <p>View the Hotels list here.</p>

                </div>
            {% endif %}


              <div class="content container">
                <div class="row">
                    <div class="col-md-12">
                        <div class="links">
                            <!-- Example row of columns -->
                            <div class="row">
                                <div class="col-md-3">
                                    <div class="thumbnail">
                                        <img src="{% static "images/hotel.jpg" %}" alt="customer"/>
                                        <div class="caption">
                                            <h2>Hotels</h2>
                                            <p>We see our success in our customers success </p>
                                            <p><a class="btn btn-primary" href="{% url 'hotel:hotels_list' %}"
                                                  role="button">View
                                                details &raquo;</a></p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
              </div>







    </body>
</html>
{% endblock %}

hotel/templates/hotel/hotels_list.html
{% extends "hotel/base.html" %}

{% load static %}

{% block title %}
  {{ Hotels }}
{% endblock %}

{% block content %}

<div class="container">
    <div class="row">
    <div class="col-lg-6 col-md-12 col-sm-12">

        {% for hotel in hotels %}

            <div class="col-sm-8">
             {% if hotel.imagesofhotel.all|length > 0 %}
                 <div id="carousel-demo" class="carousel slide" data-ride="carousel">
                 <div class="carousel-inner" role="listbox">
                 {% for image in hotel.imagesofhotel.all  %}
                             {% if forloop.counter == 1 %}
                                 <div class="item active">
                                {% else %}
                                 <div class="item">
                                     {% endif %}
                                    <div class="thumbnail">
                                    <a href="{{ image.image.url}} " target="_blank">
                                         <img src="{% if image.image %} {{ image.image.url }} {% else %} {% static "img/no_image.png"  %} {% endif %}"  style="height: 300px; width:300px;
                                         ">
                                    </a>
                                    </div>
                                </div>
                        {% endfor %}
                    </div>

            <!-- Left and right controls -->
            <a class="left carousel-control" href="#carousel-demo" role="button" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
             </a>
                <a class="right carousel-control" href="#carousel-demo" role="button" data-slide="next">
                    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
                 </div>
                </div>
                  </div>
                 {% else %}

                    <div class="col-sm-8">
                            <div class="thumbnail">

                            <a href="{% static "images/no_image.png"  %}" target="_blank">
                                <img src=" {% static "images/no_image.png"  %}"  style="height:300px; width: 300px;">
                            </a>
                            </div>
                    </div>

        {% endif %}

          <div class="column">
            <p> </p>
            <p style="color:Red;font-weight:bold">Hotel Details:</p>
                    <p> Hotel Name :{{ hotel.Name }}</p>
                    <p> Hotel Description:{{ hotel.Description }}</p>
                    <p>Hotel Amenities: {{ hotel.Amenities }}</p>
                    <p>Hotel Address:{{ hotel.Address }}</p>
                    <p>Hotel City:{{ hotel.City }}</p>
                    <p>Hotel Country:{{ hotel.Country }}</p>
                    <p>Hotel State :{{ hotel.state }}</p>
                    <p>Hotel Zipcode:{{ hotel.zipcode }}</p>
                    <p>Hotel TelephoneNumber: {{ hotel.TelephoneNumber }}</p>
                    <p><a href="{{ hotel.get_absolute_url }}"
                           class="btn btn-warning">View Hotel details</a></p>
        </div>

        {% endfor %}
         </div>
    </div>
</div>

{% endblock %}

hotel/templates/hotel/mybookings.html
{% extends 'hotel/base.html' %}
{% load static %}
{% block content %}

{% if messages %}
<ul style="color:red;font-size: 50px;">
   {% for message in messages %}
	   <li>{{ message }}</li>
   {% endfor %}
</ul>
{% endif %}




<div class="row">
  <div class="col-md-6 col-md-offset-3 ">


      <h4>My Bookings:</h4>



<!-- Loads all of the Current users reservations in a list and displays all  the details -->
    {% if bookings|length > 0 %}
      {%for booking in bookings%}
          {% if booking.CheckIn > now.date %}
        <a class="btn btn-sm btn-danger pull-right" href="{% url 'hotel:cancelbooking' booking.id %}">Cancel</a>
        <a  class="btn btn-sm btn-default pull-right "href="{% url 'hotel:gpdf' booking.id %}">Download PDF</a>
        {% endif %}

        <p>Hotel Name: {{booking.hotel.Name}}</p>
          <p>Room Number: {{booking.room.RoomNumber}}</p>
        <p>Room Type :{{booking.room.RoomType}}  </p>
        <p>Guest Name :{{booking.guestFirstName}} {{booking.guestLastName}}  </p>
        <p>Check-in Date : {{booking.CheckIn}}  </p>
        <p>Check-out Date: {{booking.CheckOut}} </p>
        <p>Total Price : ${{booking.totalPrice}} </p>

          <br>
          <br>

      {%endfor%}

        {% else %}

                    <p>There are no bookings </p>

        {% endif %}


    </div>

 <a class="btn btn-primary " href="{% url 'hotel:hotels_list' %}">View Hotels list Here</a>
  </div>
{% endblock %}

hotel/templates/hotel/room_details.html
{% extends "hotel/base.html" %}
{% load static %}

{% block title %}
  {{ RoomoftheHotel }}
{% endblock %}

{% block content %}
  <div class="Container">


     <div class="col-md-6" style="padding-left: 20px">

                    <div class="thumbnail">
                        {% if room.image %}
                            <a href="{{ room.image.url}} " target="_blank">
                             {% else %}
                             <a href="{% static "images/no_image.png"  %}" target="_blank">
                            {% endif %}
                                <img src="{% if room.image %} {{ room.image.url }} {% else %} {% static "images/no_image.png"  %} {% endif %}" alt="..." style="height:300px; width: auto">
                            </a>
                     </div>

                  </div>
                    <div class="column">
                    <p style="font-weight: bold;color: Red"> Room Details:</p>
                    <p>Room Number:{{ room.RoomNumber }}</p>
                    <p>Room Type:{{ room.RoomType }}</p>
                     <p>Room Capacity:{{ room.Capacity }}</p>
                    <p>Room Bedoption:{{ room.BedOption }}</p>
                    <p>Room Size:{{ room.RoomSize }}</p>
                    <p>Room Amenities:{{ room.Amenities }}</p>
                    <p>Room Price :${{ room.Price }}</p>
                     {% comment %}<p><a href="{{ room.get_absolute_url }}"
                           class="btn btn-warning">View Room details</a></p>{% endcomment %}

                        <p><a href="{% url 'hotel:hotel_details' id=room.hotel.id slug=room.hotel.slug  %}"
                           class="btn btn-warning">View Hotel details</a></p>
                         <p><a href="{% url 'hotel:bookroom' hotel_id=room.hotel.id RoomNumber=room.RoomNumber %}" class="btn btn-success">Book Room</a></p>
                    </div>





  </div>
{% endblock %}